export const PARTICIPATION_CARD_GREEN = "#126609";
export const PARTICIPATION_CARD_GREEN_DARK = "#0e5207";

export const PARTICIPATION_CARD_WIDTH = 391;
export const PARTICIPATION_CARD_HEIGHT = 322;
export const PARTICIPATION_CARD_ASPECT = PARTICIPATION_CARD_WIDTH / PARTICIPATION_CARD_HEIGHT;
